---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
        types: [text]
      - id: forbid-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: trailing-whitespace
      - id: check-ast
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11
